name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t subhajitpatra498/image_upload .
      - name: Publish image to docker hub
        run: docker push subhajitpatra498/image_upload:latest

  deploy:
    needs: build
    runs-on: [AWS-EC2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull subhajitpatra498/image_upload:latest
      - name: Delete old container
        run: docker rm -f image_upload-container
      - name: Run docker container
        run: docker run -e ACCESS_KEY=${{secrets.ACCESS_KEY}} -e SECRET_KEY=${{ secrets.SECRET_KEY }} -d -p 8080:8080 --name image_upload-container subhajitpatra498/image_upload
